MVCConciertosAnita/Models/CategoriaEvento.cs
namespace MVCConciertosAnita.Models
{
    public class CategoriaEvento
    {
        public int IdCategoria { get; set; }

        public string Categoria { get; set; }
    }
}

MVCConciertosAnita/Models/ErrorViewModel.cs
namespace MVCConciertosAnita.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCConciertosAnita/Models/Evento.cs
namespace MVCConciertosAnita.Models
{
    public class Evento
    {
        public int IdEvento { get; set; }

        public string Nombre { get; set; }

        public string Artista { get; set; }

        public int IdCategoria { get; set; }

        public string Imagen { get; set; }
    }
}

MVCConciertosAnita/Models/KeysModel.cs
namespace MVCConciertosAnita.Models
{
    public class KeysModel
    {
        public string MySql { get; set; }
        public string ApiEventos { get; set; }
        public string BucketName { get; set; }
        public string BucketUrl { get; set; }

    }
}

MVCConciertosAnita/Controllers/EventosController.cs
using Microsoft.AspNetCore.Mvc;
using MVCConciertosAnita.Models;
using MVCConciertosAnita.Services;

namespace MVCConciertosAnita.Controllers
{
    public class EventosController : Controller
    {
        private ServiceEventos service;

        public EventosController(ServiceEventos service)
        {
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            List<Evento> eventos = await
                this.service.GetEventos();

            ViewData["CATEGORIAS"] = await this.service.GetCategorias();
            return View(eventos);
        }

        [HttpPost]
        public async Task<IActionResult> Index(int idcategoria)
        {
            List<Evento> eventos = await
                this.service.FindEventoCategoria(idcategoria);

            ViewData["CATEGORIAS"] = await this.service.GetCategorias();
            return View(eventos);
        }
    }
}

MVCConciertosAnita/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCConciertosAnita.Models;
using System.Diagnostics;

namespace MVCConciertosAnita.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCConciertosAnita/Views/Eventos/Index.cshtml
@model IEnumerable<MVCConciertosAnita.Models.Evento>

@{
    ViewData["Title"] = "Index";
    List<CategoriaEvento> categorias = ViewData["CATEGORIAS"] as List<CategoriaEvento>;
    string UrlBucket = keysModel.BucketUrl;
}

<h1>Index</h1>

<form method="post">
    <label>Categorías</label>
    <select name="idcategoria">
        @foreach (CategoriaEvento cat in categorias)
        {
            <option value="@cat.IdCategoria">@cat.Categoria</option>
        }
    </select>
    <br />
    <button class="btn btn-success">Filtrar!</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEvento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artista)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCategoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdEvento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artista)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCategoria)
            </td>
            <td>
                <img src="@UrlBucket@item.Imagen" style="width:100px;height:100px;" />
            </td>
            
        </tr>
}
    </tbody>
</table>

MVCConciertosAnita/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCConciertosAnita/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCConciertosAnita</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCConciertosAnita.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCConciertosAnita</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Eventos" asp-action="Index">Eventos</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCConciertosAnita - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>